
meta_product_name : "Skizi"
meta_title: "Skizi- no stain without value"
meta_description : "pas le temps de perdre de l'argent voici skizi l appli pour le planning des votre entreprise"
meta_image : "cover.jpg" # devrait exister dans `app/assets/images/`
